anypoint:
  api:
    id: "20188721"
   
racer:
  timeout: "7200000" # milliseconds

openai:
  apikey: xxxxx

milvus:
  host: in05-1e384f2b1c165dc.serverless.gcp-us-west1.cloud.zilliz.com
  token: xxxxx

articles:
  ratio: "0.5"