http:
  port: "8081"
  
anypoint:
  api:
    id: "19278412"
   
#aws:
#  accessKey: xxxx
#  secretKey: yyyy
  
racer:
  timeout: "7200000" # milliseconds

challenge:
  '1brc':
    tolerance: "0.00002"